# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 998833a501e50e556c7651dbfa0746b7f1aad76c9b40d502013fce7123b4ac6160e8b1e1529070b8438e9de0acae635e0275c70e751b408e8f59c5923a994b67

test:
  secret_key_base: c43a6a2c6d8af8c38359e725d92231bf389b58633c6935de133b9d3e2c659c1382e5bc32d31c0971c9145d0a6370cb99aa4418993482797ab6766e85af38fc52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
